import { Colors } from "@/constants/Colors";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  contentContainer: {
    padding: 22,
    gap: 20,
    paddingBottom: 100,
  },
  containerTopo: {
    flexDirection: "column",
    gap: 20,
  },
  title: {
    color: Colors.primary,
    fontFamily: "Roboto-Bold",
    fontSize: 20,
    textAlign: "left",
  },
  containerBuscar: {
    position: "relative",
  },
  buscar: {
    backgroundColor: "white",
    outlineColor: "gray",
    outlineStyle: "solid",
    fontFamily: "Roboto-Medium",
    outlineWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingRight: 50,
    paddingVertical: 12,
    elevation: 2,
  },
  buscarFocused: {
    outlineColor: Colors.primary,
    outlineWidth: 2,
  },
  iconBuscar: {
    position: "absolute",
    right: 16,
    top: "50%",
    transform: [{ translateY: -10 }],
    color: 'gray',
  },
  iconLimpar: {
    position: "absolute",
    right: 16,
    top: "50%",
    transform: [{ translateY: -11 }],
    zIndex: 2,
  },
  itemContainer: {
    marginBottom: 16,
  },
  itemCard: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 20,
    gap: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: '#cbd5e1',
  },
  containerTexts: {
    gap: 4,
  },
  label: {
    textTransform: "uppercase",
    fontFamily: "Roboto-Bold",
    fontSize: 12,
    color: "#999",
  },
  valor: {
    fontFamily: "Roboto-Bold",
    fontSize: 16,
    color: "#333",
    marginBottom: 4,
  },
  btnContainer: {
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
  },
  btnExcluir: {
    flex: 1,
    backgroundColor: Colors.vermelho,
    padding: 10,
    borderRadius: 8,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  btnEditar: {
    flex: 1,
    backgroundColor: Colors.amarelo,
    padding: 10,
    borderRadius: 8,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  btnTexto: {
    color: "white",
    fontFamily: "Roboto-Medium",
    fontSize: 14,
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
  },
  emptyText: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    color: "gray",
  },
  fab: {
    position: "absolute",
    bottom: 100,
    right: 20,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: "white",
    borderRadius: 16,
    padding: 24,
    gap: 16,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 20,
    fontFamily: "Roboto-Bold",
    color: Colors.primary,
    textAlign: "center",
    marginBottom: 10,
  },
  inputGroup: {
    gap: 6,
  },
  uidContainer: {
    flexDirection: "row",
    gap: 10,
  },
  inputLabel: {
    fontFamily: "Roboto-Medium",
    color: "#666",
  },
  modalInput: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    fontFamily: "Roboto-Regular",
  },
  btnNfcScan: {
    backgroundColor: "#333",
    width: 50,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  modalActions: {
    flexDirection: "row",
    gap: 12,
    marginTop: 10,
  },
  btnCancelar: {
    flex: 1,
    padding: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ccc",
    alignItems: "center",
  },
  btnSalvar: {
    flex: 1,
    backgroundColor: Colors.primary,
    padding: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  txtCancelar: {
    fontFamily: "Roboto-Bold",
    color: "#666",
  },
  txtSalvar: {
    fontFamily: "Roboto-Bold",
    color: "white",
  },
  scanModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.85)",
    justifyContent: "center",
    alignItems: "center",
  },
  scanModalCard: {
    backgroundColor: "white",
    padding: 30,
    borderRadius: 20,
    alignItems: "center",
    width: "80%",
  },
  scanActivity: {
    marginBottom: 20,
  },
  scanIcon: {
    marginBottom: 20,
  },
  scanTextTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
    textAlign: "center",
  },
  scanTextBody: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    marginBottom: 20,
  },
  btnScanCancel: {
    backgroundColor: Colors.vermelho,
    paddingVertical: 10,
    paddingHorizontal: 30,
    borderRadius: 8,
  },
  txtScanCancel: {
    color: "white",
    fontWeight: "bold",
  },
  accessDeniedContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 22,
  },
  accessDeniedCard: {
    backgroundColor: "white",
    borderRadius: 16,
    padding: 40,
    alignItems: "center",
    gap: 20,
    width: "100%",
    maxWidth: 400,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 5,
  },
  accessDeniedTitle: {
    fontSize: 24,
    fontFamily: "Roboto-Bold",
    color: Colors.primary,
    textAlign: "center",
  },
  accessDeniedText: {
    fontSize: 16,
    fontFamily: "Roboto-Regular",
    color: "#666",
    textAlign: "center",
    lineHeight: 24,
  },
  btnLogin: {
    backgroundColor: Colors.primary,
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 8,
    width: "100%",
    alignItems: "center",
    marginTop: 10,
  },
  btnLoginText: {
    color: "white",
    fontSize: 16,
    fontFamily: "Roboto-Bold",
  },
});