import { Colors } from "@/constants/Colors";
import { StyleSheet, Platform } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  contentContainer: {
    padding: 22,
    gap: 20,
    paddingBottom: 100,
  },
  containerTopo: {
    flexDirection: "column",
    gap: 20,
  },
  title: {
    color: Colors.primary,
    fontFamily: "Roboto-Bold",
    fontSize: 20,
    textAlign: "left",
  },
  containerBuscar: {
    position: "relative",
  },
  buscar: {
    backgroundColor: "white",
    outlineColor: "gray",
    outlineStyle: "solid",
    fontFamily: "Roboto-Medium",
    outlineWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 16,
    paddingRight: 50,
    paddingVertical: 12,
    elevation: 2,
  },
  buscarFocused: {
    outlineColor: Colors.primary,
    outlineWidth: 2,
  },
  iconBuscar: {
    position: "absolute",
    right: 16,
    top: "50%",
    transform: [{ translateY: -10 }],
    color: "gray",
  },
  iconLimpar: {
    position: "absolute",
    right: 16,
    top: "50%",
    transform: [{ translateY: -11 }],
    zIndex: 2,
  },
  itemContainer: {
    marginBottom: 16,
  },
  itemCard: {
    backgroundColor: "white",
    borderRadius: 12,
    padding: 20,
    gap: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: "#cbd5e1",
  },
  itemHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
  },
  itemImageContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: "#f0f0f0",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 15,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "#ddd",
  },
  itemImage: {
    width: "100%",
    height: "100%",
  },
  containerTexts: {
    flex: 1,
  },
  label: {
    textTransform: "uppercase",
    fontFamily: "Roboto-Bold",
    fontSize: 12,
    color: "#999",
  },
  valor: {
    fontFamily: "Roboto-Bold",
    fontSize: 16,
    color: "#333",
    marginBottom: 4,
  },
  btnContainer: {
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
  },
  btnExcluir: {
    flex: 1,
    backgroundColor: Colors.vermelho,
    padding: 10,
    borderRadius: 8,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  btnEditar: {
    flex: 1,
    backgroundColor: Colors.amarelo,
    padding: 10,
    borderRadius: 8,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
  },
  btnVer: {
    backgroundColor: "#3b82f6",
    marginRight: 5,
  },
  btnTexto: {
    color: "white",
    fontFamily: "Roboto-Medium",
    fontSize: 14,
  },
  emptyContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
  },
  emptyText: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    color: "gray",
  },
  fab: {
    position: "absolute",
    bottom: 100,
    right: 20,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: Colors.primary,
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: "white",
    borderRadius: 16,
    padding: 24,
    gap: 16,
    elevation: 5,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 20,
    fontFamily: "Roboto-Bold",
    color: Colors.primary,
    textAlign: "center",
    marginBottom: 10,
  },
  modalTitleNoMargin: {
    marginBottom: 0,
  },
  imagePickerContainer: {
    alignItems: "center",
    marginBottom: 20,
  },
  imagePreview: {
    width: 120,
    height: 120,
    borderRadius: 14,
    backgroundColor: "#f0f0f0",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: Colors.primary,
    borderStyle: "dashed",
    overflow: "hidden",
  },
  imageFull: {
    width: "100%",
    height: "100%",
  },
  imagePlaceholderText: {
    fontSize: 10,
    color: "#999",
    marginTop: 5,
  },
  imageChangeText: {
    color: Colors.primary,
    fontSize: 14,
    marginTop: 8,
    fontWeight: "500",
  },
  inputGroup: {
    gap: 6,
    marginBottom: 12,
  },
  uidContainer: {
    flexDirection: "row",
    gap: 10,
  },
  inputLabel: {
    fontFamily: "Roboto-Medium",
    color: "#666",
  },
  modalInput: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    fontFamily: "Roboto-Regular",
  },
  inputMultiline: {
    height: 80,
    textAlignVertical: "top",
  },
  btnNfcScan: {
    backgroundColor: "#333",
    width: 50,
    borderRadius: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  modalActions: {
    flexDirection: "row",
    gap: 12,
    marginTop: 10,
  },
  btnCancelar: {
    flex: 1,
    padding: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ccc",
    alignItems: "center",
  },
  btnSalvar: {
    flex: 1,
    backgroundColor: Colors.primary,
    padding: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  txtCancelar: {
    fontFamily: "Roboto-Bold",
    color: "#666",
  },
  txtSalvar: {
    fontFamily: "Roboto-Bold",
    color: "white",
  },
  detailImageContainer: {
    width: "100%",
    aspectRatio: 1,
    backgroundColor: "#f5f5f5",
    borderRadius: 12,
    marginBottom: 20,
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#eee",
  },
  detailInfoBox: {
    backgroundColor: "#f9f9f9",
    padding: 15,
    borderRadius: 8,
    marginBottom: 10,
  },
  detailValueTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
  },
  detailValueMono: {
    fontSize: 16,
    fontFamily: Platform.OS === "ios" ? "Courier" : "monospace",
    color: "#555",
  },
  detailValueText: {
    fontSize: 16,
    color: "#444",
  },
  btnEditLarge: {
    backgroundColor: Colors.primary,
    padding: 15,
    borderRadius: 10,
    alignItems: "center",
    marginBottom: 10,
  },
  rowCenter: {
    flexDirection: "row",
    alignItems: "center",
  },
  btnTextLarge: {
    color: "white",
    fontWeight: "bold",
    fontSize: 16,
    marginLeft: 8,
  },

  // Scan Modal
  scanModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.85)",
    justifyContent: "center",
    alignItems: "center",
  },
  scanModalCard: {
    backgroundColor: "white",
    padding: 30,
    borderRadius: 20,
    alignItems: "center",
    width: "80%",
  },
  scanActivity: {
    marginBottom: 20,
  },
  scanIcon: {
    marginBottom: 20,
  },
  scanTextTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
    textAlign: "center",
  },
  scanTextBody: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    marginBottom: 20,
  },
  btnScanCancel: {
    backgroundColor: Colors.vermelho,
    paddingVertical: 10,
    paddingHorizontal: 30,
    borderRadius: 8,
  },
  txtScanCancel: {
    color: "white",
    fontWeight: "bold",
  },
});
